services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: Bookify.Api/Dockerfile
    depends_on:
      bookify-db:
        condition: service_healthy

  bookify-db:
    image: postgres:17
    container_name: Bookify.db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - bookify-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "127.0.0.1", "-U", "postgres", "-d", "bookify"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
    ports:
      - 5432:5432

volumes:
  bookify-db-data:
